services:
  selenium:
    image: selenium/standalone-chrome:4.24.0
    shm_size: 2g
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:4444/wd/hub/status | jq -r .value.ready | grep -q true"]
      interval: 5s
      timeout: 3s
      retries: 20

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    depends_on:
      selenium:
        condition: service_healthy
    environment:
      SELENIDE_REMOTE:  "http://selenium:4444/wd/hub"
      SELENIDE_BROWSER: "chrome"
      SELENIDE_TIMEOUT: "10000"
      APP_HEADLESS: "true"
    tty: true
